### ISSUE TITLE
[FEATURE] Add Chat Page

### ISSUE THREAD

**Issue by AbdelrahmanBadwy** [AbdelrahmanBadwy/Lawyer_Assistant_App#3]
# Tasks
- [x] #7
- [x] Connection DB
- [x] #8
- [x] API Connection Server
- [x] #10
- [x] Res The response From Server and view 
- [x] Store Chat in DB
- [x] #27
- [x] #14
- [x] #11
- [x] #23
- [x] #30
# Resources
https://qss-stock.devsecstudio.com/templates.php
https://youtu.be/zjWfDEUsobQ?si=9Q5_4HY3bOubaHmv
