### ISSUE TITLE
[FEATURE] Backend Server

### ISSUE THREAD

**Issue by MohamedMagdy097** [AbdelrahmanBadwy/Lawyer_Assistant_App#5]
# Tasks
___
## For the OpenAI API Assistant
- [x] Assistant's instructions prompt
- [x] Create new threads get request /new
- [x] Chat with the assistant post request /chat
- [x] Delete a thread post request /delete
### Reference : 
https://platform.openai.com/docs/assistants/overview
https://platform.openai.com/docs/api-reference
---
## For the Postgres Database
- [x] Register new account post request /register
- [x] Login existing account post /login
- [x] Create new To-do post request /create
- [x] Delete an existing To-do post request /deletetodo
- [x] Search for a user by name post request /namesearch
- [x] Search for a user by email post request /emailsearch
### Reference :
https://console.neon.tech/app/projects
